# Generated by Django 4.0.2 on 2022-02-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_article', models.CharField(max_length=150, verbose_name="ім'я статьї")),
                ('text_article', models.TextField(verbose_name='Текст статьї')),
                ('pub_date', models.DateTimeField(verbose_name='дата публікації стітьї')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=40, verbose_name="ім'я користувача")),
                ('text_comment', models.TextField(verbose_name='Самий коментарії')),
                ('date_comment', models.DateTimeField(verbose_name='дата публікації коментарія')),
                ('articale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article')),
            ],
        ),
    ]
